- name: Configure Mysql
  hosts: 192.168.200.102
  vars_files:
    - vars/db_vars.yaml
  tasks:
  - name: Install, configure and running DataBase Debian
    import_tasks: installPackageDeb.yaml
    when: ansible_facts['os_family'] == "Debian"
  - name: Install, configure and running DataBase RedHat
    import_tasks: installPackageRedH.yaml
    when: ansible_facts['os_family'] == "RedHat"
  handlers:
    - name: Mysql Service Restart
      service:
        name: mysql
        state: restarted
    - name: Mysqld Service Restart
      service:
        name: mysqld
        satte: restarted

- name: Configure wordpress service
  hosts: 192.168.200.101
  vars_files:
    - vars/wp_vars.yaml
  tasks:
  - name: Download wordpress
    get_url:
      url: https://wordpress.org/wordpress-5.8.tar.gz 
      dest: /home/devops/wordpress-5.8.tar.gz
    async: 120
    poll: 0
    register: down_result
  - name: Install Package apache2 Debian
    import_tasks: debpackage.yaml
    when: ansible_facts['os_family'] == "Debian"
  - name: Install Package httpd, php RedHat
    import_tasks: redpackage.yaml
    when: ansible_facts['os_family'] == "RedHat"
  - name: sync
    async_status:
      jid: "{{ down_result.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: 100
    delay: 5
  - name: unarchive and config
    import_tasks: unarchive-config.yaml
  - name: Change Service port in Debian
    template:
      src: jinja/ports.j2
      dest: /etc/apache2/ports.conf
      force: yes
    notify: 
    - Restart apache2
    when: ansible_facts['os_family'] == "Debian"
  - name: Change Service port in Redhat
    template:
      src: jinja/portsrh.j2
      dest: /etc/httpd/conf/httpd.conf
      force: yes
    notify:
    - Restart httpd
    when: ansible_facts['os_family'] == "RedHat"
  handlers:
    - name: Restart apache2
      service:
        name: apache2
        state: restarted
    - name: Restart httpd
      service:
        name: httpd
        state: restarted
  post_tasks:
  - name: Check Web Status using uri
    uri:
      url: "http://192.168.200.101:{{ port_var.service_port }}/wordpress"
      status_code: 200
      return_content: yes
