- name: UnArchiving wordpress file
  unarchive:
    src: /home/devops/wordpress-5.8.tar.gz
    dest: /var/www/html/
    remote_src: yes
- name: Copy & Setting wp-config.ph with template
  template:
    src: jinja/wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php
