- name: Configure Mysql
  hosts: dbserver
  roles:
    - database
- name: Configure wordpress service
  hosts: webserver
  roles:
    - wordpress
  post_tasks:
    - name: Check Web Status using uri
      uri:
        url: "http://{{ groups['webserver'][0] }}:{{ service_port }}/wordpress"
        status_code: 200
        return_content: yes
